### ISSUE TITLE
Is it a working copy ?

### ISSUE THREAD

**Issue by jvmvik** [swilliams-pivotal/gradle-plugin#2]
Please, can you provide a quick usage example ?
I have lot of trouble to write a correct gradle script ro run vertx because of the verticles must be remove from the classpath. if I understand correctly this comment :

``` java
  // Can't have the app on the vert.x classpath
  classpath = files( classpath.findAll {
    !( it.toString() ==~ /.+build\/(classes|resources)\/main$/ )
  } )
```

This problem is also affecting any java launcher like IDEA.

**Comment by pidster** [comment]
I'm rewriting this at the moment... expect a release soon.
